CONFIG = {
    "TOKENIZER_DIR": "./model/tokenizer",
    "DATA_PATH": "./data/processed/model/pretraining_preprocessed.txt",
    "OUTPUT_DIR": "./model/ReELECTRA/pretrained/checkpoints",
    "FINAL_SAVE_DIR": "./model/ReELECTRA/pretrained",
    "MAX_LENGTH": 128,
    "MLM_PROB": 0.15,
    "DISCRIMINATOR_LR": 1e-4,
    "GENERATOR_LR_FACTOR": 0.5,
    "WARMUP_STEPS": 10000,
    "NUM_EPOCHS_CPU": 1,
    "NUM_EPOCHS_CUDA": 2,
    "BATCH_CPU": 2,
    "BATCH_CUDA": 16,
    "GRAD_ACCUM_CPU": 8,
    "GRAD_ACCUM_CUDA": 1,
    "DATALOADER_WORKERS_CPU": 0,
    "DATALOADER_WORKERS_CUDA": 2,
    "SAVE_STEPS": 1000,
    "LOGGING_STEPS": 50,
}
